#Get all books
GET http://localhost:3001/books HTTP/1.1
Content-Type: aplication/json

###

#Create a Book
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title": "Harry Potter"
}

###

#Edit book with id 1
PUT http://localhost:3001/books/1 HTTP/1.1
Content-type: application/json

{
    "title":"Dark Tower"
}

###

#Delete book with id 1
DELETE http://localhost:3001/books/1 HTTP/1.1
Content-type: aplication/json

#Testing API JSON-server with REST-Client extension